apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: main
      image: busybox
      command: ["sleep","65535"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      csi:
        driver: image.stager.csi.k8s.io
        volumeAttributes:
          stage-in/image: busybox:latest
