version: "3.7"
services:
  workspace:
    # buildah requires privileged container
    privileged: true
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
      - BUILADH_IMG=quay.io/buildah/stable:v1.12.0
    command: sleep 65535
    working_dir: /workspace
    volumes:
      - ../:/workspace
    ports:
      - 2345:2345
  registory:
    image: registry:2.3.0
    ports:
    - 5000:5000